[[blinds]]
name = "DebugRoller"
[blinds.mock]
[blinds.servo]
pulse_width_delta = 400
full_cycle_time = 100

[[blinds]]
name = "DebugVenetian"
[blinds.mock]
[blinds.servo]
pulse_width_delta = 400
full_tilt_time = 1
full_cycle_time = 100
