services:
  blinds_hap:
    image: ghcr.io/thinkier/blinds_hap
    restart: always
    network_mode: host
    volumes:
      - ./config:/app/config
      - ./persist:/app/persist
    devices:
      - /dev/serial0
    environment:
      # The logs totally didn't blow up above 9GiB and crowd out the rest of the OS
      DEBUG: BlindsHAP:*,-BlindsHAP:Proto:*
