pin = "69696969"

[[blinds]]
name = "BleRoller"
[blinds.ble]
[blinds.servo]
pulse_width_retract = 1000
pulse_width_extend = 1700
full_cycle_time = 100

[[blinds]]
name = "BleVenetian"
[blinds.ble]
name = "BleVenetian DEAD BEEF"
[blinds.servo]
pulse_width_retract = 1000
pulse_width_extend = 1700
full_tilt_time = 1
full_cycle_time = 100
