pin = "69696969"

[[blinds]]
name = "MockRoller"
[blinds.mock]
[blinds.servo]
pulse_width_retract = 1000
pulse_width_extend = 1700
pulse_width_retract_tilt = 1100
pulse_width_extend_tilt = 1900
full_cycle_time = 100

[[blinds]]
name = "MockVenetian"
[blinds.mock]
[blinds.servo]
pulse_width_retract = 1000
pulse_width_extend = 1700
pulse_width_retract_tilt = 1100
pulse_width_extend_tilt = 1900
full_tilt_time = 1
full_cycle_time = 100
